### ISSUE TITLE
USI2.0の要望/提案

### ISSUE THREAD

**Issue by qhapaq-49** [yaneurao/MyShogi#24]
USI2.0の仕様について。現状のponder周りのデータのやり取りには問題があると思います。
データのやり取りが大変面倒であり、特に、WCSC28でのHefeweizenの活躍の原動力となったmulti ponderをやるのに不便であると考えています。

【multi ponderを入れるときに不便だと感じたこと】
１．go ponderを行うときに自分の持ち時間が表示されない
２．ponderがあたった時に、ponderhitしか送られずに、相手の消費時間がわからない
３．ponderが外れた時stopが送られるが、この時、エンジン側がbestmove（ponderが間違っているのでilleagalな手になる）を返す、かつそのbestmoveはponderで考慮した局面に対してlegalでなければならない

３が特に面倒です。multi ponderを行う場合、guiエンジンがponderが外れたと思っていても実際はあたっている(multi ponderの候補の中にあたりの手がある)ことがあるため、stopを無視して、その後のposition命令からmulti ponderがhitしたかを確認したいので、bestmove None などの適当な文字列を使ってguiをやり過ごしたいのにそれが出来ないからです。

【解決案】
１．bestmove move1 ponder ponder1 ponder2 ... と複数のponderを投げられるようにする
２．go ponder の後ろに持ち時間の情報をつける　例： go ponder btime 10000 wtime 10000
３．ponderhit の後ろに１で指定したどのponderが当たったか、および持ち時間の情報をつける　ponderhit ponder1 btime 10000 wtime 10000
4.ponderが外れた時のstop命令の次に送られてくるbestmoveに対して、手がlegalであるかのチェックを行わない

以上、ご検討いただければ幸いです

**Comment by qhapaq-49** [comment]
書くだけ書いて ponder1 ponder2 ...と大量にponderを送った場合、go ponderも大量に送らねばならないことに気づきました。後方互換性的にはこのやり方は面倒な気がするので改定案

【解決案２】
1．go ponder の後ろに持ち時間の情報をつける　例： go ponder btime 10000 wtime 10000
2．ponderhit の後ろに持ち時間の情報をつける　ponderhit btime 10000 wtime 10000
3.ponderが外れた時のstop命令の次に送られてくるbestmoveに対して、手がlegalであるかのチェックを行わない

解決案の１を外しただけです。

**Comment by muzudho** [comment]
info の文字エンコーディングは UTF-8 に拡張したらどうだぜ。 ☖☗⛉⛊

🐗🐇🐈🐕🐆🐕🐈🐇🐗
　🦒　　　　　🐘　
🐤🐤🐤🐤🐤🐤🐤🐤🐤



🐤🐤🐤🐤🐤🐤🐤🐤🐤
　🐘　　　　　🦒　
🐗🐇🐈🐕🐆🐕🐈🐇🐗

**Comment by yaneurao** [comment]
qhapaq-49さん
> １．go ponderを行うときに自分の持ち時間が表示されない

持ち時間は渡したほうが良いですね。"byoyomi"も先後両方の分を渡すべきでしょうし。そうすると思います。

> ２．ponderがあたった時に、ponderhitしか送られずに、相手の消費時間がわからない

はい、これは修正されるべきですね。そうすると思います。

> ３．ponderが外れた時(snip)そのbestmoveはponderで考慮した局面に対してlegalでなければならない

こんな制約はないのでは…。

あとmulti ponderについてはGUI側で対応しようと思っています。(｀･ω･´)ｂ
思考エンジン側、プロトコル側の修正はなくて済みます。

例) GUI側の設定で"multi ponder 5"になっていれば5つのインスタンスを生成して、指定秒(通例0.1秒とか)だけ1つ目のインスタンスでMultiPV 5で探索して、5つの候補手を得て、それらに対して、5つのインスタンスで"go ponder"します。そのあとponderhitしたインスタンスに対してだけ"ponderhit"を送信して、残りのインスタンスにはstopを送ります。

**Comment by yaneurao** [comment]
muzudho
> info の文字エンコーディングは UTF-8 に拡張したらどうだぜ。 ☖☗⛉⛊

・プロトコル上、UTF-8を強制するかどうか
・GUI側でどう対応するか(GUIの設定でsjis、UTF-8の解釈を選べるようにするなど)
・思考エンジン側(やねうら王の場合)、いまC++で書いてあって、これがsjisで漢字でメッセージを出力してるところがあったりして、UTF-8と混在させたくない。(デバッガーやコマンドプロンプトに出力するとき、sjisのほうが扱いやすかったりするのが理由)
など色んな問題が噴出しそう…。

とりま、懸案事項として留めておきます。

**Comment by yaneurao** [comment]
issueで議論書くのあまり筋がよくなさげなので、いったんcloseします。また別のところで…。
