### ISSUE TITLE
バグ・要望等　総合受付

### ISSUE THREAD

**Issue by yaneurao** [yaneurao/MyShogi#33]
バグ、要望等はこちらにお願いします。

GitHubのアカウントをお持ちでない方は、メールでも構いません。( yaneurao@gmail.com )
βテスターの方は、Slackのほうで報告お願いします。

Twitterでのバグ報告に対しては返信できないことがあります。予めご了承ください。

**Comment by endo4917** [comment]
詰将棋のkifファイルが読み込めません。
手合割と初期画面文字列が同時に指定されています。
とありますので、柿木将棋に対応していないということかもしれませんが、この程度は許容していただかないと実用になりません。

**Comment by yaneurao** [comment]
お手数、おかけして申し訳ありません。本件はGitHub上では修正済みの問題で、Update1にてその修正が反映されます。よろしくお願いいたします。

**Comment by endo4917** [comment]
ということで手合割を除去したファイルを作ってtanuki詰将棋を試していますが、速い、速い。余詰検索は考えていらっしゃるでしょうか。

**Comment by yaneurao** [comment]
余詰検索の必要性は私は理解しているのですが、その詰将棋エンジンの作者のtanuki-さんが、そっち方面、あまり興味がないようですね…。

**Comment by endo4917** [comment]
tanuki-さんは、詰将棋のルールの変遷をご存知なのでしょうか。玉方最長、攻方最短、手駒余らず程度で考えていらっしゃるのではないかと思います。余詰作が詰将棋の作品としては失格になっていること、余詰の検討が人間には非常に大変であること、そもそも何をもって余詰というのかがはっきりしないことをご理解いただき、柿木将棋の知恵も借りて、背尾詰では２０通り（？）まで探しているようですので、そのくらいで手を打って余詰探索を実装していただきたいと思います。せっかくこれだけのスピードで詰めの探索ができているのに、ここでとどまるのはもったいないです。MorePreciseMateまで来ているので、その候補を見せてくれればいいだけです。ご説得！をお願いします。

**Comment by endo4917** [comment]
昨晩はダウンロードして、ちょっと遊んで寝てしまいましたが、今朝になっていろいろやると、残念ながら詰将棋エンジンというには力不足のようです。GUIの注文はあるものの、詰将棋鑑賞は柿木将棋と将棋所＋脊尾詰で当面は行くことにします。「コンピュータ向け超難解詰将棋作品集」が解けたら教えてください。

そもそも棋力が低いので、鑑賞するだけなのですが、普通の対局の方は今年の６月５日の藤井聡太vs石田直裕戦の67手目あたりから76手目77飛成のあたりの評価値の変化を見て喜んでいます。こちらは読み筋が複数出ていますね。

**Comment by yaneurao** [comment]
要望・バグ報告、GitHubのissueを使うのは筋が悪いようなので、以降、ブログ記事のコメント欄のほうを使うことにして、ここはcloseします。

- とりま、Update2まではこちらで。→　[『将棋神やねうら王』Update2までの遊戯施設](
http://yaneuraou.yaneu.com/2018/09/06/%E3%80%8E%E5%B0%86%E6%A3%8B%E7%A5%9E%E3%82%84%E3%81%AD%E3%81%86%E3%82%89%E7%8E%8B%E3%80%8Fupdate2%E3%81%BE%E3%81%A7%E3%81%AE%E9%81%8A%E6%88%AF%E6%96%BD%E8%A8%AD/)
