### ISSUE TITLE
Aperyのbook.binが読み込めない件

### ISSUE THREAD

**Issue by tttak** [yaneurao/MyShogi#57]
更新履歴.txtに記載されておりますAperyのbook.binが読み込めない件ですが、
YaneuraOu（エンジン）側のbook.cppで以下の箇所が"BookDir"を使用していないからではないでしょうか？

```
	static const constexpr char* kAperyBookName = "book/book.bin";
```

```
		if (filename == kAperyBookName) {
			// Apery定跡データベースを読み込む
			//	apery_book = std::make_unique<AperyBook>(kAperyBookName);
			// これ、C++14の機能。C++11用に以下のように書き直す。
			apery_book = std::unique_ptr<AperyBook>(new AperyBook(kAperyBookName));
		}
```

```
		if (book_name == kAperyBookName) {
```

**Comment by yaneurao** [comment]
私もそれかと思ったんですけど、BookDirが反映されてて"../../book/book.bin"を見に行っているようで、そこにファイルを置くと確かにファイルが存在しない旨のエラーは消えるんですけど、定跡の指し手を選んでくれないという感じで、きっちりデバッガーで追いかけないと原因がわかりそうになくて、後回しにしてます。何かわかったら教えてください(´ω｀)人

**Comment by yaneurao** [comment]
なお、ファイル自体は、まふさんの公開されている一番新しい定跡ファイルのApery用のやつでテストしました。

http://www.mafujyouseki.com/article/455477728.html

**Comment by tttak** [comment]
早速のご返答ありがとうございます。
確かにBookDirが反映されて"../../book/book.bin"が読み込まれるのですが、
Apery形式の定跡としてではなく、やねうら王形式の定跡として読み込まれてしまっているように見えます。

実際、book.binを"../../book"に置かなかった際のファイルが存在しない旨のエラーは
"could not open an apery book file. ../../book/book.bin"（Apery形式の定跡の読み込みエラー）
ではなく
"Error! : can't read ../../book/book.bin"（やねうら王形式の定跡の読み込みエラー）
だったのではないかと思います。

つまり、読み込む定跡ファイルのパスとしてはBookDirが反映されるのですが、
MemoryBook::read_book()内で定跡の形式を判定する際に
「filename（../../book/book.bin）とkAperyBookName（book/book.bin）が一致しないので、Apery形式ではなくやねうら王形式」
と判定してしまっているようです。

※MemoryBook::read_book()だけではなく、MemoryBook::find()の方も同様のようです。
※同じ理由で、no_bookも正しく判定できていないように見えます。

**Comment by yaneurao** [comment]
うおー！そんな罠が！修正しときます(´ω｀)ｂ

**Comment by yaneurao** [comment]
修正できました。本件、ありがとうございました。> tttakさん
https://github.com/yaneurao/YaneuraOu/commit/ac44452e6da8a5ef9e6fbe7ca7eeeb59181838b0
