### ISSUE TITLE
なぜこのように実行されるのですか、設定が間違っているのはどこですか?

### ISSUE THREAD

**Issue by h1014179971** [yaneurao/MyShogi#67]
![image](https://user-images.githubusercontent.com/51565334/232437668-f6ab09d1-cd3a-4c00-ba15-9d101307a6b1.png)

**Comment by yaneurao** [comment]
本GitHubのプロジェクトに画像素材は含まれておりません。

**Comment by h1014179971** [comment]
こんにちは、myshogiにはマンマシンバトルAIが含まれていますか？ または、他の AI をリンクする必要がありますか? ありがとうございます




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 上午8:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yaneurao/MyShogi] なぜこのように実行されるのですか、設定が間違っているのはどこですか? (Issue #67)






本网站のプロジェクトに画像素材は含まれておりません。

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by yaneurao** [comment]
思考エンジンは含まれていません。USIプロトコル対応の思考エンジンを別途ご用意ください。

**Comment by h1014179971** [comment]
YaneuraOu さんに、将棋 AI エンジンのソース コードの詳細な説明、またはマンマシン バトル用のコードの AI 部分の具体的な説明があればお尋ねしてもよろしいですか。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 上午9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yaneurao/MyShogi] なぜこのように実行されるのですか、設定が間違っているのはどこですか? (Issue #67)





 
思考エンジンは含まれていません。USIプロトコル対応の思考エンジンを別途ご用意ください。

**Comment by yaneurao** [comment]
USIプロトコル : http://shogidokoro.starfree.jp/usi.html
将棋の思考エンジンのソースコード解説 : https://www.amazon.co.jp/exec/obidos/ASIN/B09KNGV1QT/aaaaab0c-22/ref=nosim/

**Comment by h1014179971** [comment]
こんにちは、MyShogi プロジェクトの完全版とリソースを送ってもらえますか? どうもありがとう




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaneurao/MyShogi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 上午9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaneurao/MyShogi] なぜこのように実行されるのですか、設定が間違っているのはどこですか? (Issue #67)





 
USIプロトコル : http://shogidokoro.starfree.jp/usi.html
 将棋の思考エンジンのソースコード解説 : https://www.amazon.co.jp/exec/obidos/ASIN/B09KNGV1QT/aaaaab0c-22/ref=nosim/

**Comment by yaneurao** [comment]
ソースコードはこのGitHubで公開されているものがすべてです。

画像リソースは、製品版に含まれています。(この製品に含まれる画像は二次配布は禁止です)
https://www.amazon.co.jp/exec/obidos/ASIN/B07DL34R4W/aaaaab0c-22/ref=nosim/

**Comment by h1014179971** [comment]
こんにちは、yaneuraou c ++はエンジンが正常に実行されると考えることができますか？ コンパイル後に生成されたEXEファイルは、公式Webサイトのダウンロードよりもはるかに小さいです。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaneurao/MyShogi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaneurao/MyShogi] なぜこのように実行されるのですか、設定が間違っているのはどこですか? (Issue #67)





 
ソースコードはこのGitHubで公開されているものがすべてです。
 
画像リソースは、製品版に含まれています。(この製品に含まれる画像は二次配布は禁止です)
 https://www.amazon.co.jp/exec/obidos/ASIN/B07DL34R4W/aaaaab0c-22/ref=nosim/

**Comment by h1014179971** [comment]
こんにちは、https://github.com/yaneurao/YaneuraOu のソース コードが必要です。購入することもできます。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaneurao/MyShogi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月20日(星期四) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaneurao/MyShogi] なぜこのように実行されるのですか、設定が間違っているのはどこですか? (Issue #67)





 
ソースコードはこのGitHubで公開されているものがすべてです。
 
画像リソースは、製品版に含まれています。(この製品に含まれる画像は二次配布は禁止です)
 https://www.amazon.co.jp/exec/obidos/ASIN/B07DL34R4W/aaaaab0c-22/ref=nosim/

**Comment by yaneurao** [comment]
> yaneuraou c ++はエンジンが正常に実行されると考えることができますか？

やねうら王を始めとしてUSIプロトコル対応の思考エンジンは、MyShogiから思考エンジンとして登録して使うことができます。

また、USIプロトコル対応のGUIとして将棋所があります。↓
まずは将棋所で動作を検証してみてください。

将棋所 : http://shogidokoro.starfree.jp/

**Comment by h1014179971** [comment]
1. 思考エンジンで exe ファイルを正常にコンパイルでき、思考エンジンは正常に動作するはずです。
2. 思考エンジンに「isready」コマンドを送信し、その思考によって「readyok」が返され、次に「usinewgame」コマンドを思考エンジンに送信し、1 秒待ってから「 position startpos move 7g7f" と "go mate∞" コマンドを実行しても、ThinkEngine は "bestmove" を返しません。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yaneurao/MyShogi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yaneurao/MyShogi] なぜこのように実行されるのですか、設定が間違っているのはどこですか? (Issue #67)





  
yaneuraou c ++はエンジンが正常に実行されると考えることができますか？
  
やねうら王を始めとしてUSIプロトコル対応の思考エンジンは、MyShogiから思考エンジンとして登録して使うことができます。
 
また、USIプロトコル対応のGUIとして将棋所があります。↓
 まずは将棋所で動作を検証してみてください。
 
将棋所 : http://shogidokoro.starfree.jp/

**Comment by yaneurao** [comment]
それは評価関数がないからです。

本プロジェクトは、思考エンジンの動作のさせ方がわからない人をサポートするためにあるのではありません。

将棋所で思考エンジンを設定して動作するところまでは自力で解決してください。
将棋所 : http://shogidokoro.starfree.jp/
